# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'
inhibit_all_warnings!

target 'InstagramFirebase' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstagramFirebase
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

end
